# Generated by Django 3.2.4 on 2021-06-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'articulos',
                'db_table': 'articulos',
                'ordering': ['id'],
            },
        ),
    ]
