# Generated by Django 3.2.4 on 2021-06-17 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_articulo_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fecha',
            new_name='fecha_creacion',
        ),
    ]
